services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG:-false}
      KAFKA_BROKERS: kafka:9092
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: ${REVERB_HOST}
      REVERB_PORT: ${REVERB_PORT}
      REVERB_SCHEME: ${REVERB_SCHEME}
    image: php:8.3-fpm-alpine
    ports:
      - '${APP_PORT:-8585}:8585'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    extra_hosts:
      - "registry.yarnpkg.com:104.16.0.35"
      - "packagist.org:138.199.36.11"
      - "registry-1.docker.io:44.205.109.198"
    container_name: marketplace_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - './docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini'
    networks:
      - marketplace_app
    healthcheck:
      test: [ "CMD", "php", "artisan", "about", "--only=environment" ]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 300s
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy

  reverb:
    image: php:8.3-fpm-alpine
    command: php artisan reverb:start --host=0.0.0.0 --port=${REVERB_SERVER_PORT:-8080}
    ports:
      - "${REVERB_SERVER_PORT:-8080}:${REVERB_SERVER_PORT:-8080}"
    volumes:
      - .:/var/www/html
    networks:
      - marketplace_app
    depends_on:
      app:
        condition: service_healthy

  pgsql:
    image: 'postgres:16-alpine'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql-data:/var/lib/postgresql/data'
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - marketplace_app
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - marketplace_app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  scheduler:
    profiles:
      - dev-tools
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      php artisan schedule:work
    volumes:
      - .:/var/www/html
    networks:
      - marketplace_app
    depends_on:
      app:
        condition: service_healthy

  mailpit:
    profiles:
      - dev-tools
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - marketplace_app

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'meilisearch-data:/meili_data'
    networks:
      - marketplace_app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  kafka:
    profiles:
      - kafka
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    ports:
      - "9094:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - 'kafka-data:/var/lib/kafka/data'
    networks:
      - marketplace_app
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server 127.0.0.1:9092 --list || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG:-false}
      KAFKA_BROKERS: kafka:9092
      REVERB_APP_ID: ${REVERB_APP_ID}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: ${REVERB_HOST}
      REVERB_PORT: ${REVERB_PORT}
      REVERB_SCHEME: ${REVERB_SCHEME}
    command: >
      php artisan horizon
    volumes:
      - .:/var/www/html
    networks:
      - marketplace_app
    depends_on:
      app:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
    profiles:
      - monitoring
    image: prom/prometheus:v2.47.2
    ports:
      - '9090:9090'
    volumes:
      - './prometheus:/etc/prometheus'
      - 'prometheus-data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - marketplace_app
    depends_on:
      app:
        condition: service_healthy

  grafana:
    profiles:
      - monitoring
    image: grafana/grafana:10.1.5
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - './grafana/provisioning:/etc/grafana/provisioning'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-password}
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_DATASOURCE_HTTP_CLIENT_ALLOW_HOST_REGEX=clickhouse
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - marketplace_app
    depends_on:
      prometheus:
        condition: service_started
      clickhouse:
        condition: service_healthy

  clickhouse:
    # profiles:
    #   - monitoring
    image: clickhouse/clickhouse-server:latest
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP interface
      - "9001:9000" # Native protocol
    volumes:
      - ./clickhouse/initdb:/docker-entrypoint-initdb.d
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "password"
    networks:
      - marketplace_app
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok'" ]
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      app:
        condition: service_healthy

  recommendation_service:
    profiles:
      - kafka
    build:
      context: ./services/recommendation_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      CLICKHOUSE_PORT: 9000
    networks:
      - marketplace_app
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  nlp_search_preprocessing:
    build:
      context: ./services/nlp_search_preprocessing
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - marketplace_app
    depends_on:
      app:
        condition: service_healthy

  image_analysis_service:
    profiles:
      - kafka
    build:
      context: ./services/image_analysis_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      KAFKA_BROKER: kafka:9092
      LARAVEL_APP_HOST: app:8585
    networks:
      - marketplace_app
    depends_on:
      app:
        condition: service_healthy
      kafka:
        condition: service_healthy

  image_analysis_consumer:
    profiles:
      - kafka
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      php artisan kafka:consume --topics=image_analysis_completed --consumer=App\\Kafka\\Consumers\\ImageAnalysisConsumer
    volumes:
      - .:/var/www/html
    networks:
      - marketplace_app
    depends_on:
      app:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgsql:
        condition: service_healthy

networks:
  marketplace_app:
    driver: bridge

volumes:
  pgsql-data:
    driver: local
  redis-data:
    driver: local
  meilisearch-data:
    driver: local
  kafka-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  clickhouse-data:
    driver: local
