services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG:-false}
      KAFKA_BROKERS: kafka:9092
      PUSHER_HOST: soketi
    # SUPERVISOR_PHP_COMMAND: >
    #   php -d variables_order=EGPCS artisan octane:start --watch --server=roadrunner --host=0.0.0.0 --rpc-port=6001 --port=8585
    image: php:8.3-fpm-alpine
    ports:
      - '${APP_PORT:-8585}:8585'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    command: php artisan serve --host=0.0.0.0 --port=8585
    # command: php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8585
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - './docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini'
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "php", "artisan", "about", "--only=environment"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 300s
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: 'postgres:16-alpine'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql-data:/var/lib/postgresql/data'
      - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis-data:/data'
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    restart: unless-stopped
    command: >
      php artisan schedule:work
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      app:
        condition: service_healthy

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - laravel

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'meilisearch-data:/meili_data'
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:7700/health"]
      retries: 3
      timeout: 5s

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - 'kafka-data:/var/lib/kafka/data'
    networks:
      - laravel
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 10

  soketi:
    image: quay.io/soketi/soketi:latest
    container_name: soketi
    restart: unless-stopped
    environment:
      DEBUG: 1
      METRICS_ENABLED: 'true'
      SOKETI_DEFAULT_APP_ID: local
      SOKETI_DEFAULT_APP_KEY: local
      SOKETI_DEFAULT_APP_SECRET: local
    ports:
      - "6001:6001"
      - "9601:9601"
    networks:
      - laravel

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horizon
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG:-false}
    command: >
      php artisan horizon
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      app:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - '9090:9090'
    volumes:
      - './prometheus:/etc/prometheus'
      - 'prometheus-data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - laravel
    depends_on:
      - app

  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - './grafana/provisioning:/etc/grafana/provisioning'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-password}
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_DATASOURCE_HTTP_CLIENT_ALLOW_HOST_REGEX=clickhouse
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - laravel
    depends_on:
      - prometheus
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP interface
      - "9001:9000" # Native protocol
    volumes:
      - ./clickhouse/initdb:/docker-entrypoint-initdb.d
      - clickhouse-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "password"
    networks:
      - laravel
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok'"]
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      - app

networks:
  laravel:
    driver: bridge

volumes:
  pgsql-data:
    driver: local
  redis-data:
    driver: local
  meilisearch-data:
    driver: local
  kafka-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  clickhouse-data:
    driver: local
