apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_ds
    access: proxy
    jsonData:
      defaultDatabase: default
      host: clickhouse
      port: 8123
      protocol: http
      username: default
    secureJsonData:
      password: "password"
